# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA/nowone/SnakeGame/SnakeGame.srcs/sources_1/ip/dist_mem_gen_4/dist_mem_gen_4.xci
# IP: The module: 'dist_mem_gen_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/nowone/SnakeGame/SnakeGame.gen/sources_1/ip/dist_mem_gen_4/dist_mem_gen_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/FPGA/nowone/SnakeGame/SnakeGame.srcs/sources_1/ip/dist_mem_gen_4/dist_mem_gen_4.xci
# IP: The module: 'dist_mem_gen_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/nowone/SnakeGame/SnakeGame.gen/sources_1/ip/dist_mem_gen_4/dist_mem_gen_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
